[book]
authors = ["kephin"]
language = "en"
multilingual = false
src = "src"
title = "keep_learning();"

[build]
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
smart-punctuation = true
mathjax-support = true

[output.html.fold]
enable = true

[output.html.playground]
editable = true
line-numbers = true

[rust]
edition = "2021"
